version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis_container
    environment:
      POSTGRES_DB: geospatial_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d geospatial_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
